{
 "title": "Prometeus",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "http_server_request_duration_seconds_count (Throughput (RPS))",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 0 },
   "fieldConfig": { "defaults": { "unit": "reqps" } },
   "targets": [
    {
     "expr": "sum(rate(http_server_request_duration_seconds_count[$__rate_interval]))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "http_server_active_requests",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 0 },
   "targets": [
    { "expr": "http_server_active_requests", "legendFormat": "__auto" }
   ]
  },
  {
   "title": "http_server_request_duration_seconds (Latency (p50, p95, p99))",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "expr": "histogram_quantile(0.5, sum(rate(http_server_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.95, sum(rate(http_server_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    },
    {
     "expr": "histogram_quantile(0.99, sum(rate(http_server_request_duration_seconds_bucket[$__rate_interval])) by (le))",
     "legendFormat": "__auto"
    }
   ]
  },
  {
   "title": "GC",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 11, "x": 12, "y": 8 },
   "targets": [
    { "expr": "dotnet_gc_collections_total", "legendFormat": "__auto" },
    {
     "expr": "dotnet_gc_heap_total_allocated_bytes_total",
     "legendFormat": "__auto"
    }
   ]
  }
 ]
}